name:                haytracer
version:             0.0.1
github:              "AndreiUlmeyda/haytracer"
license:             MIT
author:              "Adrian Schurz"
maintainer:          "ulmeyda.smile@gmail.com"
copyright:           "2024 Adrian Schurz"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Ray Tracing 3D renderer, programming exercise
# category:            3D graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AndreiUlmeyda/haytracer#readme>

default-extensions: DerivingStrategies InstanceSigs

dependencies:
- base >= 4.7 && < 5

ghc-options:
  - -O2
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wmonomorphism-restriction
  - -Wmissing-local-signatures
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wcpp-undef
  - -Wmissing-deriving-strategies
  - -Wunused-packages
  - -Wunused-type-patterns
  - -Wcompat

library:
  source-dirs: src

executables:
  haytracer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haytracer

tests:
  haytracer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haytracer
    - hspec
